// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Fullscreen image lightbox with portal rendering. */

export { default } from "./components/Lightbox"
export * from "./components/Lightbox"
export { getLightboxToken } from "./tokens"
